DROP TABLE IF EXISTS transaction_saledetails;

CREATE TABLE transaction_saledetails
(
	SaleDetailsID 	BIGINT PRIMARY KEY AUTO_INCREMENT,
	SaleID			BIGINT,
	ItemID 			BIGINT NOT NULL,
	ItemDetailsID	BIGINT NULL,
	BranchID		INT,
	Quantity		DOUBLE,
	BuyPrice		DOUBLE,
	SalePrice		DOUBLE,
	Discount		DOUBLE,
	PrintCount		SMALLINT,
	PrintedDate		DATETIME,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy		VARCHAR(255) NULL,
	FOREIGN KEY(SaleID) REFERENCES transaction_sale(SaleID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(ItemID) REFERENCES master_item(ItemID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(BranchID) REFERENCES master_branch(BranchID) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE UNIQUE INDEX SALEDETAILS_INDEX
ON transaction_saledetails (SaleDetailsID, SaleID, ItemID, BranchID);