DROP TABLE IF EXISTS transaction_pick;

CREATE TABLE transaction_pick
(
	PickID 			BIGINT PRIMARY KEY AUTO_INCREMENT,
	BookingID	 	BIGINT,
	TransactionDate DATETIME NOT NULL,
	Remarks			TEXT,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL
)ENGINE=InnoDB;

CREATE UNIQUE INDEX PICK_INDEX
ON transaction_pick (PickID, BookingID);