DROP TABLE IF EXISTS master_table;

CREATE TABLE master_table
(
	TableID 		BIGINT PRIMARY KEY AUTO_INCREMENT,
	TableNumber		VARCHAR(100),
	TableStatusID	SMALLINT,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy		VARCHAR(255) NULL,
	FOREIGN KEY(TableStatusID) REFERENCES master_tablestatus(TableStatusID) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE UNIQUE INDEX TABLE_INDEX
ON master_table (TableID, TableStatusID);
