DROP TABLE IF EXISTS master_period;

CREATE TABLE master_period
(
	PeriodID	BIGINT PRIMARY KEY AUTO_INCREMENT,
	StartDate	DATE NOT NULL,
	EndDate		DATE NOT NULL,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 	VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 	VARCHAR(255) NULL
)ENGINE=InnoDB;


CREATE UNIQUE INDEX PERIOD_INDEX
ON master_period (PeriodID);
