DROP TABLE IF EXISTS master_project;

CREATE TABLE master_project
(
	ProjectID 	BIGINT PRIMARY KEY AUTO_INCREMENT,
	ProjectName	VARCHAR(255) NOT NULL,
	IsDone		BIT NOT NULL,
	Remarks 	TEXT,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 	VARCHAR(255) NOT NULL,
	ModifiedDate	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 	VARCHAR(255) NULL
)ENGINE=InnoDB;


CREATE UNIQUE INDEX PROJECT_INDEX
ON master_project (ProjectID);
