DROP TABLE IF EXISTS master_inventory;

CREATE TABLE master_inventory
(
	InventortID 	BIGINT PRIMARY KEY AUTO_INCREMENT,
	InventoryName	VARCHAR(255) NOT NULL
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL
)ENGINE=InnoDB;


CREATE UNIQUE INDEX INVENTORY_INDEX
ON master_inventory (InventoryID);