DROP TABLE IF EXISTS transaction_checkin

CREATE TABLE transaction_checkin
(
	CheckInID 		BIGINT PRIMARY KEY AUTO_INCREMENT,
	Inve	VARCHAR(255) NOT NULL
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL
)ENGINE=InnoDB;


CREATE UNIQUE INDEX INVENTORY_INDEX
ON master_inventory (InventoryID);