DROP TABLE IF EXISTS master_sales;

CREATE TABLE master_sales
(
	SalesID			BIGINT PRIMARY KEY AUTO_INCREMENT,
	SalesName		VARCHAR(255) NOT NULL,
	Alias			VARCHAR(4) NOT NULL,
	Telephone 		VARCHAR(100) NOT NULL,
	Address 		VARCHAR(255),
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL
)ENGINE=InnoDB;

CREATE UNIQUE INDEX SALES_INDEX
ON master_sales (SalesID);