DROP TABLE IF EXISTS master_brand;

CREATE TABLE master_brand
(
	BrandID			BIGINT PRIMARY KEY AUTO_INCREMENT,
	BrandName		VARCHAR(255) NOT NULL,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL
)ENGINE=InnoDB;

CREATE UNIQUE INDEX BRAND_INDEX
ON master_brand (BrandID);