DROP TABLE IF EXISTS master_type;

CREATE TABLE master_type
(
	TypeID 			BIGINT PRIMARY KEY AUTO_INCREMENT,
	TypeName		VARCHAR(255) NOT NULL,
	UnitID			BIGINT,
	BrandID 		BIGINT NOT NULL,
	ReminderCount 	INT,
	BuyPrice		DOUBLE,
	SalePrice		DOUBLE,
	Quantity		INT,
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL,
	FOREIGN KEY(BrandID) REFERENCES master_brand(BrandID) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(UnitID) REFERENCES master_unit(UnitID) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB;

CREATE UNIQUE INDEX TYPE_INDEX
ON master_type (TypeID, BrandID, UnitID);