DROP TABLE IF EXISTS master_customer;

CREATE TABLE master_customer
(
	CustomerID		BIGINT PRIMARY KEY AUTO_INCREMENT,
	CustomerName	VARCHAR(255) NOT NULL,
	Telephone 		VARCHAR(100) NOT NULL,
	Address 		VARCHAR(255),
	City			VARCHAR(100),
	CreatedDate 	DATETIME NOT NULL,
	CreatedBy 		VARCHAR(255) NOT NULL,
	ModifiedDate 	TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL,
	ModifiedBy 		VARCHAR(255) NULL
)ENGINE=InnoDB;

CREATE UNIQUE INDEX CUSTOMER_INDEX
ON master_Customer (CustomerID);